package com.vasilecoste.babylog.ui.theme

import androidx.compose.ui.graphics.Color

// "Ocean" blue theme — deep, saturated blue, with a visible blue wash on backgrounds/cards
val BlueLightPrimary = Color(0xFF0D47A1)
val BlueLightOnPrimary = Color(0xFFFFFFFF)
val BlueLightPrimaryContainer = Color(0xFF90CAF9)
val BlueLightOnPrimaryContainer = Color(0xFF001B3D)
val BlueLightSecondary = Color(0xFF0277BD)
val BlueLightSecondaryContainer = Color(0xFF81D4FA)
val BlueLightTertiary = Color(0xFF00ACC1)
val BlueLightBackground = Color(0xFFE3F2FD)
val BlueLightSurfaceVariant = Color(0xFFBBDEFB)
val BlueLightOnSurfaceVariant = Color(0xFF01579B)

val BlueDarkPrimary = Color(0xFF64B5F6)
val BlueDarkOnPrimary = Color(0xFF00305F)
val BlueDarkPrimaryContainer = Color(0xFF0D47A1)
val BlueDarkOnPrimaryContainer = Color(0xFFD6E4FF)
val BlueDarkSecondary = Color(0xFF4FC3F7)
val BlueDarkSecondaryContainer = Color(0xFF01579B)
val BlueDarkTertiary = Color(0xFF00E5FF)
val BlueDarkBackground = Color(0xFF0A1929)
val BlueDarkSurfaceVariant = Color(0xFF14293D)
val BlueDarkOnSurfaceVariant = Color(0xFFB3D4FF)

// "Blossom" pink theme — vivid magenta-pink, with a visible pink wash on backgrounds/cards
val PinkLightPrimary = Color(0xFFD81B60)
val PinkLightOnPrimary = Color(0xFFFFFFFF)
val PinkLightPrimaryContainer = Color(0xFFF8BBD0)
val PinkLightOnPrimaryContainer = Color(0xFF3E001D)
val PinkLightSecondary = Color(0xFFC2185B)
val PinkLightSecondaryContainer = Color(0xFFF48FB1)
val PinkLightTertiary = Color(0xFFFF7043)
val PinkLightBackground = Color(0xFFFFF0F5)
val PinkLightSurfaceVariant = Color(0xFFF8BBD0)
val PinkLightOnSurfaceVariant = Color(0xFF880E4F)

val PinkDarkPrimary = Color(0xFFFF80AB)
val PinkDarkOnPrimary = Color(0xFF5F0030)
val PinkDarkPrimaryContainer = Color(0xFFAD1457)
val PinkDarkOnPrimaryContainer = Color(0xFFFFD9E3)
val PinkDarkSecondary = Color(0xFFF06292)
val PinkDarkSecondaryContainer = Color(0xFF880E4F)
val PinkDarkTertiary = Color(0xFFFF8A65)
val PinkDarkBackground = Color(0xFF2A0A16)
val PinkDarkSurfaceVariant = Color(0xFF3D1120)
val PinkDarkOnSurfaceVariant = Color(0xFFFFCDD8)

// Grayscale "Default" theme
val GrayLightPrimary = Color(0xFF424242)
val GrayLightOnPrimary = Color(0xFFFFFFFF)
val GrayLightPrimaryContainer = Color(0xFFE0E0E0)
val GrayLightOnPrimaryContainer = Color(0xFF212121)
val GrayLightSecondary = Color(0xFF616161)
val GrayLightSecondaryContainer = Color(0xFFF5F5F5)
val GrayLightTertiary = Color(0xFF757575)
val GrayLightBackground = Color(0xFFFAFAFA)
val GrayLightSurfaceVariant = Color(0xFFEEEEEE)
val GrayLightOnSurfaceVariant = Color(0xFF424242)

val GrayDarkPrimary = Color(0xFFE0E0E0)
val GrayDarkOnPrimary = Color(0xFF212121)
val GrayDarkPrimaryContainer = Color(0xFF424242)
val GrayDarkOnPrimaryContainer = Color(0xFFF5F5F5)
val GrayDarkSecondary = Color(0xFFBDBDBD)
val GrayDarkSecondaryContainer = Color(0xFF323232)
val GrayDarkTertiary = Color(0xFF9E9E9E)
val GrayDarkBackground = Color(0xFF121212)
val GrayDarkSurfaceVariant = Color(0xFF1E1E1E)
val GrayDarkOnSurfaceVariant = Color(0xFFE0E0E0)
